{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubechronicle.namespace" . }}
  labels:
    {{- include "kubechronicle.labels" . | nindent 4 }}
{{- end }}
