{{- if and .Values.api.enabled .Values.patterns.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubechronicle.fullname" . }}-api
  namespace: {{ include "kubechronicle.namespace" . }}
  labels:
    {{- include "kubechronicle.componentLabels" (list . "api") | nindent 4 }}
{{- end }}
