{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubechronicle.fullname" . }}-ui
  namespace: {{ include "kubechronicle.namespace" . }}
  labels:
    {{- include "kubechronicle.componentLabels" (list . "ui") | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "kubechronicle.componentSelectorLabels" (list . "ui") | nindent 4 }}
{{- end }}
