apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubechronicle

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: kubechronicle
  app.kubernetes.io/component: ui

images:
  - name: kubechronicle/ui
    newName: kubechronicle/ui
    newTag: latest
