{{- if and .Values.webhook.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubechronicle.serviceAccountName" . }}
  namespace: {{ include "kubechronicle.namespace" . }}
  labels:
    {{- include "kubechronicle.componentLabels" (list . "webhook") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
